###
# Configuration for Vagrant
###
name: tyomaa-starter
language: fi
#production:
  # This is used to automatically fetch data from a staging/production environment
  #domain: example.seravo.com
  #ssh_port: 12345
  #url: https://example.seravo.com
#staging:
  #domain: https://example.seravo.com
  #ssh_port: 54321
  #url: https://example.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications or Avahi
  domains:
    - tyomaa-starter.local
  # If you want to automatically pull stuff from production use 'always' or set
  # to 'never' to just silience the 'yes/no' question during 'vagrant up'.
  #pull_production_db: always
  #pull_production_plugins: always
  #pull_production_themes: always
  # If you want to use zeroconf (.local domains) in your network you can use this.
  #avahi: true
